root_project_name = "dev"
root_project_description = "devlopment project for local testing"
root_repo_name = "teamcity-test"
root_repo_fetch_url = "github.com:spookiej/teamcity-test.git"
root_repo_key_spec = "id_rsa"
root_repo_username = "git"